
include: package:flutter_lints/flutter.yaml

linter:
  
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_unnecessary_containers: true
    always_declare_return_types: true
    prefer_single_quotes: true
    directives_ordering: true
    # prefer_relative_imports: true

